---
title: "Trade-off between deep learning for species identification and inference about predator-prey co-occurrence: Reproducible `R` workflow integrating models in computer vision and ecological statistics"
author: "Olivier Gimenez, Maëlis Kervellec, Jean-Baptiste Fanjul, Anna Chaine, Lucile Marescot, Yoann Bollet, Christophe Duchamp"
date: "`r Sys.Date()`"
always_allow_html: true
output:
  html_document:
    highlight: tango
    theme: yeti
    toc: yes
    toc_depth: 2
    number_sections: yes
link-citations: yes
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(tidy = FALSE, 
                      fig.width = 8, 
                      fig.height = 8, 
                      echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      cache = FALSE)
options(htmltools.dir.version = FALSE)
set.seed(2022) # because 2019, 2020 and 2021 were not great
library(tidyverse)
theme_set(theme_light(base_size = 14))
library(fastai)
library(kableExtra)
```

```{r}
# download
#URLs_ADULT_SAMPLE()

# read data
df <- read_csv('adult_sample/adult.csv')
# again
dep_var <- 'salary'
cat_names <- c('workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race')
cont_names <- c('age', 'fnlwgt', 'education-num')

procs <- list(FillMissing(),Categorify(),Normalize())

dls <- TabularDataTable(df, procs, cat_names, cont_names,
      y_names = dep_var, splits = list(c(1:32000),c(32001:32561))) %>%
      dataloaders(bs = 64)

model <- dls %>% tabular_learner(layers=c(200,100), metrics=accuracy)
model %>% summary()
```


```{r}
model %>% fit(5, lr = 10^-1)
model %>% plot_loss(dpi = 200)
```


```{r}
model %>% get_confusion_matrix()
interp <- ClassificationInterpretation_from_learner(model)
interp %>% plot_confusion_matrix(dpi = 90,figsize = c(6,6))
```

```{r}
model %>% predict(df[10:15,])
```

```{r}
exp <- ShapInterpretation(model,n_samples = 20)
```

```{r}
exp %>% decision_plot(class_id = 1, row_idx = 2)
```

```{r}
exp %>% dependence_plot('age', class_id = 0)
```

```{r}
exp %>% summary_plot()
```

